// TT Bet Tracker — canonical data file.
// Updated by engine.py (recommendations) and by the app / Claude (bets).
window.BETS_FILE = {
  "settings": {
    "unitSize": 10,
    "startingBankrollUnits": 100
  },
  "recommendations": [
    {
      "id": "rec-cz-g676ps9znomsokr",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "g676ps9znomsokr",
      "playerA": "Matous Klimenta",
      "playerB": "Michal Zahradka",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 40 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1467 (n=4) vs 1550 (n=40)"
    },
    {
      "id": "rec-cz-vrqwys2d1j4f4kn",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "vrqwys2d1j4f4kn",
      "playerA": "Jan Zajicek",
      "playerB": "Josef Medek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 5 and 0 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1573 (n=5) vs 1500 (n=0)"
    },
    {
      "id": "rec-cz-ndkzlsdpmp9axq3",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ndkzlsdpmp9axq3",
      "playerA": "Vaclav Nohejl",
      "playerB": "Urbaniec Radim",
      "myProbA": 0.652,
      "marketProbA": 0.5,
      "bestOdds": 1.83,
      "edge": 0.152,
      "rec": "BET 1.00u on Vaclav Nohejl @ -120 (aiscore line)",
      "units": 1.0,
      "pickName": "Vaclav Nohejl",
      "grade": "C",
      "reasoning": "Elo 1613 (n=26) vs 1504 (n=48)"
    },
    {
      "id": "rec-cz-zrkn1spyrxluw7l",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "zrkn1spyrxluw7l",
      "playerA": "Antonin Schneeberger",
      "playerB": "Jasek, Milan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 11 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1476 (n=11) vs 1524 (n=8)"
    },
    {
      "id": "rec-cz-ndqm1sye4r6frqv",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ndqm1sye4r6frqv",
      "playerA": "Kolek, Matyas",
      "playerB": "Alois Kanak",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 12 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1564 (n=12) vs 1440 (n=4)"
    },
    {
      "id": "rec-cz-m2q10s6ygn3cek6",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "m2q10s6ygn3cek6",
      "playerA": "Damian Bucko",
      "playerB": "Adam Duch",
      "myProbA": 0.592,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Damian Bucko (59%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1582 (n=19) vs 1518 (n=14)"
    },
    {
      "id": "rec-cz-8lk2xsdz5xpfzq3",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "8lk2xsdz5xpfzq3",
      "playerA": "David Hons",
      "playerB": "Richard Vavricka",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 16 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1387 (n=16) vs 1479 (n=8)"
    },
    {
      "id": "rec-cz-jr7o1sogj3dfgk0",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "jr7o1sogj3dfgk0",
      "playerA": "Tomas Kindl",
      "playerB": "Michal Raska",
      "myProbA": 0.488,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Michal Raska (51%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1504 (n=16) vs 1513 (n=23)"
    },
    {
      "id": "rec-cz-527rxsrdvwma47e",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "527rxsrdvwma47e",
      "playerA": "Vladislav Reska",
      "playerB": "Petr Chlad",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 12 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1545 (n=12) vs 1476 (n=8)"
    },
    {
      "id": "rec-cz-9gkl1sjx36nbmqx",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "9gkl1sjx36nbmqx",
      "playerA": "Tomas Rein",
      "playerB": "Jaroslav Dohnal",
      "myProbA": 0.324,
      "marketProbA": 0.337,
      "bestOdds": 1.4,
      "edge": 0.013,
      "rec": "NO BET (edge 1.3% @ aiscore line +175/-250)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1444 (n=16) vs 1572 (n=20)"
    },
    {
      "id": "rec-cz-ezk9zsw20rrs17n",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ezk9zsw20rrs17n",
      "playerA": "Filip Wolf",
      "playerB": "Dmytro Opanasiuk",
      "myProbA": 0.618,
      "marketProbA": 0.589,
      "bestOdds": 1.57,
      "edge": 0.029,
      "rec": "NO BET (edge 2.9% @ aiscore line -175/+125)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1492 (n=12) vs 1409 (n=17)"
    },
    {
      "id": "rec-cz-l6keds42955cv75",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "l6keds42955cv75",
      "playerA": "Cernik, Jan",
      "playerB": "Zdenek Bilek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 0 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1490 (n=4) vs 1500 (n=0)"
    },
    {
      "id": "rec-cz-o17p1slw6g6fy7j",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "o17p1slw6g6fy7j",
      "playerA": "Daniel Priesol",
      "playerB": "Kvasnicka, Radim",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 7 and 0 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1424 (n=7) vs 1500 (n=0)"
    },
    {
      "id": "rec-cz-wv78lsy429wbokr",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "wv78lsy429wbokr",
      "playerA": "Martin Huk",
      "playerB": "Tomas Zahradnik",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 36 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1502 (n=36) vs 1470 (n=4)"
    },
    {
      "id": "rec-cz-63kv1s5pz15uxke",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "63kv1s5pz15uxke",
      "playerA": "Blaha, Michal",
      "playerB": "Tyn, Daniel",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 8 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1424 (n=8) vs 1532 (n=4)"
    },
    {
      "id": "rec-cz-vmqyosx1p84sgk9",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "vmqyosx1p84sgk9",
      "playerA": "Guzy Karol",
      "playerB": "Krzysztof Zapala",
      "myProbA": 0.671,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Guzy Karol (67%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1615 (n=33) vs 1490 (n=32)"
    },
    {
      "id": "rec-cz-wv78lsy4jx5sokr",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "wv78lsy4jx5sokr",
      "playerA": "Jan Vidourek",
      "playerB": "Jirasek Martin",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 20 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1529 (n=4) vs 1651 (n=20)"
    },
    {
      "id": "rec-cz-g676ps9zwrjbokr",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "g676ps9zwrjbokr",
      "playerA": "Frantisek Chaloupka",
      "playerB": "Michal Raska",
      "myProbA": 0.466,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Michal Raska (53%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1489 (n=17) vs 1513 (n=23)"
    },
    {
      "id": "rec-cz-ezk9zsw25g2h17n",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "ezk9zsw25g2h17n",
      "playerA": "Jiri Vanous",
      "playerB": "Petr Chlad",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1467 (n=4) vs 1476 (n=8)"
    },
    {
      "id": "rec-cz-vrqwys2dn9mi4kn",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "vrqwys2dn9mi4kn",
      "playerA": "Marek Hluchy",
      "playerB": "Jean-Baptiste Cousin",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 12 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1468 (n=4) vs 1505 (n=12)"
    },
    {
      "id": "rec-cz-ndqm1syeo3nsrqv",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "ndqm1syeo3nsrqv",
      "playerA": "Vojtech Jirout",
      "playerB": "Ondrej Kadavy",
      "myProbA": 0.277,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Ondrej Kadavy (72%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1428 (n=12) vs 1595 (n=20)"
    },
    {
      "id": "rec-cz-vrqwys2d154f4kn",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "vrqwys2d154f4kn",
      "playerA": "Michal Zahradka",
      "playerB": "Filip Wolf",
      "myProbA": 0.582,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Michal Zahradka (58%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1550 (n=40) vs 1492 (n=12)"
    },
    {
      "id": "rec-cz-ndqm1sye469brqv",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ndqm1sye469brqv",
      "playerA": "Urbaniec Radim",
      "playerB": "Martin Huk",
      "myProbA": 0.503,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Urbaniec Radim (50%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1504 (n=48) vs 1502 (n=36)"
    },
    {
      "id": "rec-cz-g676ps9znjmiokr",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "g676ps9znjmiokr",
      "playerA": "Jasek, Milan",
      "playerB": "Daniel Priesol",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 8 and 7 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1524 (n=8) vs 1424 (n=7)"
    },
    {
      "id": "rec-cz-9gkl1sjxlxytmqx",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "9gkl1sjxlxytmqx",
      "playerA": "Josef Medek",
      "playerB": "Cernik, Jan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 0 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1500 (n=0) vs 1490 (n=4)"
    },
    {
      "id": "rec-cz-o07d1s4ryxpfm7n",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "o07d1s4ryxpfm7n",
      "playerA": "Alois Kanak",
      "playerB": "Blaha, Michal",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1440 (n=4) vs 1424 (n=8)"
    },
    {
      "id": "rec-cz-o17p1slwzp2fy7j",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "o17p1slwzp2fy7j",
      "playerA": "Damian Bucko",
      "playerB": "Pawel Kos ",
      "myProbA": 0.627,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Damian Bucko (63%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1582 (n=19) vs 1492 (n=26)"
    },
    {
      "id": "rec-cz-34kges4ln1efeqo",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "34kges4ln1efeqo",
      "playerA": "David Hons",
      "playerB": "Jirasek Martin",
      "myProbA": 0.179,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Jirasek Martin (82%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1387 (n=16) vs 1651 (n=20)"
    },
    {
      "id": "rec-cz-6975ysxpvnnugq2",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "6975ysxpvnnugq2",
      "playerA": "Jakub Volny",
      "playerB": "Tomas Kindl",
      "myProbA": 0.509,
      "marketProbA": 0.5,
      "bestOdds": 1.83,
      "edge": 0.009,
      "rec": "NO BET (edge 0.9% @ aiscore line -120/-120)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1511 (n=13) vs 1504 (n=16)"
    },
    {
      "id": "rec-cz-j3742s6ge9mtgko",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "j3742s6ge9mtgko",
      "playerA": "Karel Zeman",
      "playerB": "Vladislav Reska",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 12 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1527 (n=4) vs 1545 (n=12)"
    },
    {
      "id": "rec-cz-l6keds42e6otv75",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "l6keds42e6otv75",
      "playerA": "Tomas Rein",
      "playerB": "Jean-Baptiste Cousin",
      "myProbA": 0.413,
      "marketProbA": 0.277,
      "bestOdds": 3.4,
      "edge": 0.136,
      "rec": "BET 1.00u on Tomas Rein @ +240 (aiscore line)",
      "units": 1.0,
      "pickName": "Tomas Rein",
      "grade": "C",
      "reasoning": "Elo 1444 (n=16) vs 1505 (n=12)"
    },
    {
      "id": "rec-cz-jek35sp49d0u97o",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "jek35sp49d0u97o",
      "playerA": "Martin Cerny",
      "playerB": "David Bochnak",
      "myProbA": 0.491,
      "marketProbA": 0.486,
      "bestOdds": 1.9,
      "edge": 0.005,
      "rec": "NO BET (edge 0.5% @ aiscore line -111/-125)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1493 (n=23) vs 1500 (n=16)"
    },
    {
      "id": "rec-cz-63kv1s5pzerfxke",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "63kv1s5pzerfxke",
      "playerA": "Zdenek Bilek",
      "playerB": "Jan Zajicek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 0 and 5 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1500 (n=0) vs 1573 (n=5)"
    },
    {
      "id": "rec-cz-34kges4lv60feqo",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "34kges4lv60feqo",
      "playerA": "Dmytro Opanasiuk",
      "playerB": "Matous Klimenta",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 17 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1409 (n=17) vs 1467 (n=4)"
    },
    {
      "id": "rec-cz-o07d1s4ry9wam7n",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "o07d1s4ry9wam7n",
      "playerA": "Tomas Zahradnik",
      "playerB": "Vaclav Nohejl",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 26 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1470 (n=4) vs 1613 (n=26)"
    },
    {
      "id": "rec-cz-wv78lsy42lmaokr",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "wv78lsy42lmaokr",
      "playerA": "Kvasnicka, Radim",
      "playerB": "Antonin Schneeberger",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 0 and 11 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1500 (n=0) vs 1476 (n=11)"
    },
    {
      "id": "rec-cz-g676ps9znxxhokr",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "g676ps9znxxhokr",
      "playerA": "Tyn, Daniel",
      "playerB": "Kolek, Matyas",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 12 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1532 (n=4) vs 1564 (n=12)"
    },
    {
      "id": "rec-cz-jr7o1sogjdeugk0",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "jr7o1sogjdeugk0",
      "playerA": "Blazej Gola",
      "playerB": "Adam Duch",
      "myProbA": 0.468,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Adam Duch (53%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1495 (n=15) vs 1518 (n=14)"
    },
    {
      "id": "rec-cz-xvkjds1wonei8k9",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "xvkjds1wonei8k9",
      "playerA": "Richard Vavricka",
      "playerB": "Jan Vidourek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 8 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1479 (n=8) vs 1529 (n=4)"
    },
    {
      "id": "rec-cz-ndkzlsdp9lnaxq3",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "ndkzlsdp9lnaxq3",
      "playerA": "Frantisek Chaloupka",
      "playerB": "Tomas Kindl",
      "myProbA": 0.478,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Tomas Kindl (52%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1489 (n=17) vs 1504 (n=16)"
    }
  ],
  "bets": [
    {
      "id": "bet-rec-cz-ndkzlsdpmp9axq3",
      "recId": "rec-cz-ndkzlsdpmp9axq3",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "playerA": "Vaclav Nohejl",
      "playerB": "Urbaniec Radim",
      "pick": "Vaclav Nohejl",
      "odds": 1.83,
      "units": 1.0,
      "grade": "C",
      "status": "pending",
      "circuit": "czech",
      "notes": "auto-logged by engine [rec:rec-cz-ndkzlsdpmp9axq3]",
      "matchId": "ndkzlsdpmp9axq3"
    },
    {
      "id": "bet-rec-cz-l6keds42e6otv75",
      "recId": "rec-cz-l6keds42e6otv75",
      "date": "2026-07-10",
      "event": "TT Cup",
      "playerA": "Tomas Rein",
      "playerB": "Jean-Baptiste Cousin",
      "pick": "Tomas Rein",
      "odds": 3.4,
      "units": 1.0,
      "grade": "C",
      "status": "pending",
      "circuit": "czech",
      "notes": "auto-logged by engine [rec:rec-cz-l6keds42e6otv75]",
      "matchId": "l6keds42e6otv75"
    }
  ]
};
