// TT Bet Tracker — canonical data file.
// Updated by engine.py (recommendations) and by the app / Claude (bets).
window.BETS_FILE = {
  "settings": {
    "unitSize": 10,
    "startingBankrollUnits": 100
  },
  "recommendations": [
    {
      "id": "rec-cz-g676ps9znomsokr",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "g676ps9znomsokr",
      "playerA": "Matous Klimenta",
      "playerB": "Michal Zahradka",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 40 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1467 (n=4) vs 1550 (n=40)"
    },
    {
      "id": "rec-cz-vrqwys2d1j4f4kn",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "vrqwys2d1j4f4kn",
      "playerA": "Jan Zajicek",
      "playerB": "Josef Medek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 5 and 0 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1573 (n=5) vs 1500 (n=0)"
    },
    {
      "id": "rec-cz-ndkzlsdpmp9axq3",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ndkzlsdpmp9axq3",
      "playerA": "Vaclav Nohejl",
      "playerB": "Urbaniec Radim",
      "myProbA": 0.652,
      "marketProbA": 0.5,
      "bestOdds": 1.83,
      "edge": 0.152,
      "rec": "BET 1.00u on Vaclav Nohejl @ -120 (aiscore line)",
      "units": 1.0,
      "pickName": "Vaclav Nohejl",
      "grade": "C",
      "reasoning": "Elo 1613 (n=26) vs 1504 (n=48)"
    },
    {
      "id": "rec-cz-zrkn1spyrxluw7l",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "zrkn1spyrxluw7l",
      "playerA": "Antonin Schneeberger",
      "playerB": "Jasek, Milan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 11 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1476 (n=11) vs 1524 (n=8)"
    },
    {
      "id": "rec-cz-ndqm1sye4r6frqv",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ndqm1sye4r6frqv",
      "playerA": "Kolek, Matyas",
      "playerB": "Alois Kanak",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 12 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1564 (n=12) vs 1440 (n=4)"
    },
    {
      "id": "rec-cz-m2q10s6ygn3cek6",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "m2q10s6ygn3cek6",
      "playerA": "Damian Bucko",
      "playerB": "Adam Duch",
      "myProbA": 0.592,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Damian Bucko (59%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1582 (n=19) vs 1518 (n=14)"
    },
    {
      "id": "rec-cz-8lk2xsdz5xpfzq3",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "8lk2xsdz5xpfzq3",
      "playerA": "David Hons",
      "playerB": "Richard Vavricka",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 16 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1387 (n=16) vs 1479 (n=8)"
    },
    {
      "id": "rec-cz-jr7o1sogj3dfgk0",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "jr7o1sogj3dfgk0",
      "playerA": "Tomas Kindl",
      "playerB": "Michal Raska",
      "myProbA": 0.488,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Michal Raska (51%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1504 (n=16) vs 1513 (n=23)"
    },
    {
      "id": "rec-cz-527rxsrdvwma47e",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "527rxsrdvwma47e",
      "playerA": "Vladislav Reska",
      "playerB": "Petr Chlad",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 12 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1545 (n=12) vs 1476 (n=8)"
    },
    {
      "id": "rec-cz-9gkl1sjx36nbmqx",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "9gkl1sjx36nbmqx",
      "playerA": "Tomas Rein",
      "playerB": "Jaroslav Dohnal",
      "myProbA": 0.324,
      "marketProbA": 0.337,
      "bestOdds": 1.4,
      "edge": 0.013,
      "rec": "NO BET (edge 1.3% @ aiscore line +175/-250)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1444 (n=16) vs 1572 (n=20)"
    },
    {
      "id": "rec-cz-ezk9zsw20rrs17n",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ezk9zsw20rrs17n",
      "playerA": "Filip Wolf",
      "playerB": "Dmytro Opanasiuk",
      "myProbA": 0.618,
      "marketProbA": 0.589,
      "bestOdds": 1.57,
      "edge": 0.029,
      "rec": "NO BET (edge 2.9% @ aiscore line -175/+125)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1492 (n=12) vs 1409 (n=17)"
    },
    {
      "id": "rec-cz-l6keds42955cv75",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "l6keds42955cv75",
      "playerA": "Cernik, Jan",
      "playerB": "Zdenek Bilek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 0 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1490 (n=4) vs 1500 (n=0)"
    },
    {
      "id": "rec-cz-o17p1slw6g6fy7j",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "o17p1slw6g6fy7j",
      "playerA": "Daniel Priesol",
      "playerB": "Kvasnicka, Radim",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 7 and 0 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1424 (n=7) vs 1500 (n=0)"
    },
    {
      "id": "rec-cz-wv78lsy429wbokr",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "wv78lsy429wbokr",
      "playerA": "Martin Huk",
      "playerB": "Tomas Zahradnik",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 36 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1502 (n=36) vs 1470 (n=4)"
    },
    {
      "id": "rec-cz-63kv1s5pz15uxke",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "63kv1s5pz15uxke",
      "playerA": "Blaha, Michal",
      "playerB": "Tyn, Daniel",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 8 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1424 (n=8) vs 1532 (n=4)"
    },
    {
      "id": "rec-cz-vmqyosx1p84sgk9",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "vmqyosx1p84sgk9",
      "playerA": "Guzy Karol",
      "playerB": "Krzysztof Zapala",
      "myProbA": 0.671,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Guzy Karol (67%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1615 (n=33) vs 1490 (n=32)"
    },
    {
      "id": "rec-cz-wv78lsy4jx5sokr",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "wv78lsy4jx5sokr",
      "playerA": "Jan Vidourek",
      "playerB": "Jirasek Martin",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 20 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1529 (n=4) vs 1651 (n=20)"
    },
    {
      "id": "rec-cz-g676ps9zwrjbokr",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "g676ps9zwrjbokr",
      "playerA": "Frantisek Chaloupka",
      "playerB": "Michal Raska",
      "myProbA": 0.466,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Michal Raska (53%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1489 (n=17) vs 1513 (n=23)"
    },
    {
      "id": "rec-cz-ezk9zsw25g2h17n",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "ezk9zsw25g2h17n",
      "playerA": "Jiri Vanous",
      "playerB": "Petr Chlad",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1467 (n=4) vs 1476 (n=8)"
    },
    {
      "id": "rec-cz-vrqwys2dn9mi4kn",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "vrqwys2dn9mi4kn",
      "playerA": "Marek Hluchy",
      "playerB": "Jean-Baptiste Cousin",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 12 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1468 (n=4) vs 1505 (n=12)"
    },
    {
      "id": "rec-cz-ndqm1syeo3nsrqv",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "ndqm1syeo3nsrqv",
      "playerA": "Vojtech Jirout",
      "playerB": "Ondrej Kadavy",
      "myProbA": 0.277,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Ondrej Kadavy (72%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1428 (n=12) vs 1595 (n=20)"
    },
    {
      "id": "rec-cz-vrqwys2d154f4kn",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "vrqwys2d154f4kn",
      "playerA": "Michal Zahradka",
      "playerB": "Filip Wolf",
      "myProbA": 0.582,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Michal Zahradka (58%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1550 (n=40) vs 1492 (n=12)"
    },
    {
      "id": "rec-cz-ndqm1sye469brqv",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ndqm1sye469brqv",
      "playerA": "Urbaniec Radim",
      "playerB": "Martin Huk",
      "myProbA": 0.503,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Urbaniec Radim (50%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1504 (n=48) vs 1502 (n=36)"
    },
    {
      "id": "rec-cz-g676ps9znjmiokr",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "g676ps9znjmiokr",
      "playerA": "Jasek, Milan",
      "playerB": "Daniel Priesol",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 8 and 7 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1524 (n=8) vs 1424 (n=7)"
    },
    {
      "id": "rec-cz-9gkl1sjxlxytmqx",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "9gkl1sjxlxytmqx",
      "playerA": "Josef Medek",
      "playerB": "Cernik, Jan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 0 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1500 (n=0) vs 1490 (n=4)"
    },
    {
      "id": "rec-cz-o07d1s4ryxpfm7n",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "o07d1s4ryxpfm7n",
      "playerA": "Alois Kanak",
      "playerB": "Blaha, Michal",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1440 (n=4) vs 1424 (n=8)"
    },
    {
      "id": "rec-cz-o17p1slwzp2fy7j",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "o17p1slwzp2fy7j",
      "playerA": "Damian Bucko",
      "playerB": "Pawel Kos ",
      "myProbA": 0.627,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Damian Bucko (63%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1582 (n=19) vs 1492 (n=26)"
    },
    {
      "id": "rec-cz-34kges4ln1efeqo",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "34kges4ln1efeqo",
      "playerA": "David Hons",
      "playerB": "Jirasek Martin",
      "myProbA": 0.179,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Jirasek Martin (82%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1387 (n=16) vs 1651 (n=20)"
    },
    {
      "id": "rec-cz-6975ysxpvnnugq2",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "6975ysxpvnnugq2",
      "playerA": "Jakub Volny",
      "playerB": "Tomas Kindl",
      "myProbA": 0.509,
      "marketProbA": 0.5,
      "bestOdds": 1.83,
      "edge": 0.009,
      "rec": "NO BET (edge 0.9% @ aiscore line -120/-120)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1511 (n=13) vs 1504 (n=16)"
    },
    {
      "id": "rec-cz-j3742s6ge9mtgko",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "j3742s6ge9mtgko",
      "playerA": "Karel Zeman",
      "playerB": "Vladislav Reska",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 12 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1527 (n=4) vs 1545 (n=12)"
    },
    {
      "id": "rec-cz-l6keds42e6otv75",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "l6keds42e6otv75",
      "playerA": "Tomas Rein",
      "playerB": "Jean-Baptiste Cousin",
      "myProbA": 0.413,
      "marketProbA": 0.277,
      "bestOdds": 3.4,
      "edge": 0.136,
      "rec": "BET 1.00u on Tomas Rein @ +240 (aiscore line)",
      "units": 1.0,
      "pickName": "Tomas Rein",
      "grade": "C",
      "reasoning": "Elo 1444 (n=16) vs 1505 (n=12)"
    },
    {
      "id": "rec-cz-jek35sp49d0u97o",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "jek35sp49d0u97o",
      "playerA": "Martin Cerny",
      "playerB": "David Bochnak",
      "myProbA": 0.491,
      "marketProbA": 0.486,
      "bestOdds": 1.9,
      "edge": 0.005,
      "rec": "NO BET (edge 0.5% @ aiscore line -111/-125)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1493 (n=23) vs 1500 (n=16)"
    },
    {
      "id": "rec-cz-63kv1s5pzerfxke",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "63kv1s5pzerfxke",
      "playerA": "Zdenek Bilek",
      "playerB": "Jan Zajicek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 0 and 5 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1500 (n=0) vs 1573 (n=5)"
    },
    {
      "id": "rec-cz-34kges4lv60feqo",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "34kges4lv60feqo",
      "playerA": "Dmytro Opanasiuk",
      "playerB": "Matous Klimenta",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 17 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1409 (n=17) vs 1467 (n=4)"
    },
    {
      "id": "rec-cz-o07d1s4ry9wam7n",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "o07d1s4ry9wam7n",
      "playerA": "Tomas Zahradnik",
      "playerB": "Vaclav Nohejl",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 26 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1470 (n=4) vs 1613 (n=26)"
    },
    {
      "id": "rec-cz-wv78lsy42lmaokr",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "wv78lsy42lmaokr",
      "playerA": "Kvasnicka, Radim",
      "playerB": "Antonin Schneeberger",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 0 and 11 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1500 (n=0) vs 1476 (n=11)"
    },
    {
      "id": "rec-cz-g676ps9znxxhokr",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "g676ps9znxxhokr",
      "playerA": "Tyn, Daniel",
      "playerB": "Kolek, Matyas",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 4 and 12 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1532 (n=4) vs 1564 (n=12)"
    },
    {
      "id": "rec-cz-jr7o1sogjdeugk0",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "jr7o1sogjdeugk0",
      "playerA": "Blazej Gola",
      "playerB": "Adam Duch",
      "myProbA": 0.468,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Adam Duch (53%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1495 (n=15) vs 1518 (n=14)"
    },
    {
      "id": "rec-cz-xvkjds1wonei8k9",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "xvkjds1wonei8k9",
      "playerA": "Richard Vavricka",
      "playerB": "Jan Vidourek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 8 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1479 (n=8) vs 1529 (n=4)"
    },
    {
      "id": "rec-cz-ndkzlsdp9lnaxq3",
      "date": "2026-07-10",
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "ndkzlsdp9lnaxq3",
      "playerA": "Frantisek Chaloupka",
      "playerB": "Tomas Kindl",
      "myProbA": 0.478,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Tomas Kindl (52%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1489 (n=17) vs 1504 (n=16)"
    },
    {
      "id": "rec-pl-ezk9zsw2nx3i17n",
      "date": "2026-07-10",
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "ezk9zsw2nx3i17n",
      "playerA": "Nowak Jakub",
      "playerB": "Damian Fira",
      "myProbA": 0.543,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Nowak Jakub (54%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1474 (n=34) vs 1443 (n=24)"
    },
    {
      "id": "rec-pl-g676ps9zv9otokr",
      "date": "2026-07-10",
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "g676ps9zv9otokr",
      "playerA": "Michal Natkaniec",
      "playerB": "Lukasz Pyda",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 16 and 6 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1429 (n=16) vs 1443 (n=6)"
    },
    {
      "id": "rec-cz-ndqm1sye4n9irqv",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ndqm1sye4n9irqv",
      "playerA": "Marek Chlebecek",
      "playerB": "Trefny Jan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 5 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1551 (n=5) vs 1475 (n=4)"
    },
    {
      "id": "rec-cz-j3742s6g8y6bgko",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "j3742s6g8y6bgko",
      "playerA": "Jaroslav Strnad",
      "playerB": "Josef Pelikan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 18 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1460 (n=18) vs 1468 (n=4)"
    },
    {
      "id": "rec-cz-edq08swrxvdhekx",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "edq08swrxvdhekx",
      "playerA": "Ondrej Kucirek",
      "playerB": "Adam Svoboda",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 5 and 0 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1514 (n=5) vs 1500 (n=0)"
    },
    {
      "id": "rec-pl-l6keds42zwrsv75",
      "date": "2026-07-10",
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "l6keds42zwrsv75",
      "playerA": "Patryk Jendrzejewski",
      "playerB": "Jakub Zochniak",
      "myProbA": 0.536,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Patryk Jendrzejewski (54%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1546 (n=27) vs 1521 (n=16)"
    },
    {
      "id": "rec-pl-ezk9zsw2n31u17n",
      "date": "2026-07-10",
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "ezk9zsw2n31u17n",
      "playerA": "Wojciech Gluszek",
      "playerB": "Sebastian Baran",
      "myProbA": 0.406,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Sebastian Baran (59%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1488 (n=29) vs 1554 (n=17)"
    },
    {
      "id": "rec-pl-l6keds42z8dfv75",
      "date": "2026-07-10",
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "l6keds42z8dfv75",
      "playerA": "Pawel Adamus",
      "playerB": "Oliver Vincenec",
      "myProbA": 0.393,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Oliver Vincenec (61%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1478 (n=31) vs 1553 (n=45)"
    },
    {
      "id": "rec-pl-vmqyosx1joetgk9",
      "date": "2026-07-10",
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "vmqyosx1joetgk9",
      "playerA": " Adam Ruszkiewicz",
      "playerB": "Orszulik, Jan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 29 and 8 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1492 (n=29) vs 1498 (n=8)"
    },
    {
      "id": "rec-20260710-fumiya-igarashi-leo-de-nodrest",
      "date": "2026-07-10",
      "startTime": 1783718100,
      "event": "WTT Feeder Asuncion, MS",
      "circuit": "wtt",
      "playerA": "Leo de Nodrest",
      "playerB": "Fumiya Igarashi",
      "myProbA": 0.839,
      "marketProbA": 0.732,
      "bestOdds": 1.28,
      "edge": 0.107,
      "rec": "BET 1.00u on Leo de Nodrest @ -357 (bet365)",
      "units": 1.0,
      "grade": "C",
      "reasoning": "rank pts 575 vs 73 -> base 82%; form L10: 60% vs 60%; H2H thin (0); fatigue 0 vs 1 matches/3d | odds pulled 22:33",
      "matchId": "jr7o1soglxrigk0",
      "pickName": "Leo de Nodrest"
    },
    {
      "id": "rec-cz-527rxsrdme5i47e",
      "date": "2026-07-10",
      "startTime": 1783723500,
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "527rxsrdme5i47e",
      "playerA": "Ondrej Kadavy",
      "playerB": "Martin Cerny",
      "myProbA": 0.695,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Ondrej Kadavy (69%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1625 (n=23) vs 1482 (n=26)"
    },
    {
      "id": "rec-pl-xvkjds1w98wi8k9",
      "date": "2026-07-10",
      "startTime": 1783723800,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "xvkjds1w98wi8k9",
      "playerA": "Jacek Oracz",
      "playerB": "Dawid Pyrek",
      "myProbA": 0.679,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Jacek Oracz (68%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1665 (n=36) vs 1535 (n=27)"
    },
    {
      "id": "rec-pl-jek35sp46nvb97o",
      "date": "2026-07-10",
      "startTime": 1783723800,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "jek35sp46nvb97o",
      "playerA": "Jakub Witkowski",
      "playerB": "Jakub Zochniak",
      "myProbA": 0.339,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Jakub Zochniak (66%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1405 (n=17) vs 1521 (n=16)"
    },
    {
      "id": "rec-pl-ndqm1syex9ytrqv",
      "date": "2026-07-10",
      "startTime": 1783724100,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "ndqm1syex9ytrqv",
      "playerA": "Sokolowski, Oskar",
      "playerB": "Mateusz Sikon",
      "myProbA": 0.649,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Sokolowski, Oskar (65%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1495 (n=36) vs 1388 (n=36)"
    },
    {
      "id": "rec-pl-ndqm1syexmyarqv",
      "date": "2026-07-10",
      "startTime": 1783724100,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "ndqm1syexmyarqv",
      "playerA": "Mikolaj Lukaszewski",
      "playerB": "Piotr Staniszewski",
      "myProbA": 0.48,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Piotr Staniszewski (52%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1456 (n=45) vs 1469 (n=18)"
    },
    {
      "id": "rec-cz-ndqm1sye4v9srqv",
      "date": "2026-07-10",
      "startTime": 1783724400,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ndqm1sye4v9srqv",
      "playerA": "Patrik Pycha ",
      "playerB": "Vladimir Cermak",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 11 and 9 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1539 (n=11) vs 1491 (n=9)"
    },
    {
      "id": "rec-cz-oj7xpsvg146u4kg",
      "date": "2026-07-10",
      "startTime": 1783724400,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "oj7xpsvg146u4kg",
      "playerA": "Radek Bartunek",
      "playerB": "David Horak",
      "myProbA": 0.325,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: David Horak (67%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1388 (n=17) vs 1514 (n=13)"
    },
    {
      "id": "rec-cz-wv78lsy46e1aokr",
      "date": "2026-07-10",
      "startTime": 1783724400,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "wv78lsy46e1aokr",
      "playerA": "Pavel Kulhanek",
      "playerB": "Lubor Sulava",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 9 and 24 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1594 (n=9) vs 1569 (n=24)"
    },
    {
      "id": "rec-20260711-amy-wang-valentina-rios-salazar",
      "date": "2026-07-11",
      "startTime": 1783782600,
      "event": "WTT Feeder Asuncion, WS",
      "circuit": "wtt",
      "playerA": "Amy Wang",
      "playerB": "Valentina Rios-Salazar",
      "myProbA": 0.903,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Amy Wang (90%) — odds not found; enter odds in app",
      "units": 0,
      "grade": "C",
      "reasoning": "rank pts 685 vs 39 -> base 90%; form L10: 40% vs 50%; H2H thin (0); fatigue 1 vs 3 matches/3d",
      "matchId": "zrkn1spy2m3hw7l"
    },
    {
      "id": "rec-20260711-claire-picard-li-yu-jhun",
      "date": "2026-07-11",
      "startTime": 1783782600,
      "event": "WTT Feeder Asuncion, WS",
      "circuit": "wtt",
      "playerA": "Claire Picard",
      "playerB": "Li Yu-jhun",
      "myProbA": 0.153,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Li Yu-jhun (85%) — odds not found; enter odds in app",
      "units": 0,
      "grade": "C",
      "reasoning": "rank pts 82 vs 585 -> base 19%; form L10: 50% vs 70%; H2H thin (0)",
      "matchId": "m2q10s6ym21tek6"
    },
    {
      "id": "rec-20260711-beatriz-kanashiro-huang-yu-jie",
      "date": "2026-07-11",
      "startTime": 1783782600,
      "event": "WTT Feeder Asuncion, WS",
      "circuit": "wtt",
      "playerA": "Huang Yu-Jie",
      "playerB": "Beatriz Kanashiro",
      "myProbA": 0.887,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Huang Yu-Jie (89%) — odds not found; enter odds in app",
      "units": 0,
      "grade": "C",
      "reasoning": "rank pts 580 vs 25 -> base 91%; form L10: 50% vs 100%; H2H thin (0); fatigue 1 vs 4 matches/3d",
      "matchId": "oj7xpsvg8r0f4kg"
    },
    {
      "id": "rec-cz-oj7xpsvgyo9a4kg",
      "date": "2026-07-10",
      "startTime": 1783724100,
      "event": "TT Cup",
      "circuit": "czech",
      "matchId": "oj7xpsvgyo9a4kg",
      "playerA": "Petr Chlad",
      "playerB": "Jiri Vanous",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 11 and 7 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1465 (n=11) vs 1428 (n=7)"
    },
    {
      "id": "rec-pl-9gkl1sjx053hmqx",
      "date": "2026-07-10",
      "startTime": 1783724700,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "9gkl1sjx053hmqx",
      "playerA": "Roman Wiza",
      "playerB": "Jakub Michalski",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 24 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1468 (n=24) vs 1433 (n=4)"
    },
    {
      "id": "rec-pl-g676ps9zvpouokr",
      "date": "2026-07-10",
      "startTime": 1783725000,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "g676ps9zvpouokr",
      "playerA": "Wozniczka, Marcin",
      "playerB": "Krzysztof Malcher",
      "myProbA": 0.437,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Krzysztof Malcher (56%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1450 (n=16) vs 1494 (n=11)"
    },
    {
      "id": "rec-pl-ezk9zsw2nj1t17n",
      "date": "2026-07-10",
      "startTime": 1783725300,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "ezk9zsw2nj1t17n",
      "playerA": "Marcin Marchlewski",
      "playerB": "Patryk Jendrzejewski",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 6 and 28 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1474 (n=6) vs 1561 (n=28)"
    },
    {
      "id": "rec-pl-jr7o1sog6ylsgk0",
      "date": "2026-07-10",
      "startTime": 1783725600,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "jr7o1sog6ylsgk0",
      "playerA": "Mariusz Baron",
      "playerB": "Oliver Vincenec",
      "myProbA": 0.363,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Oliver Vincenec (64%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1468 (n=57) vs 1565 (n=46)"
    },
    {
      "id": "rec-pl-ndkzlsdpz2oaxq3",
      "date": "2026-07-10",
      "startTime": 1783725600,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "ndkzlsdpz2oaxq3",
      "playerA": "Wojciech Gluszek",
      "playerB": "Piotr Staniszewski",
      "myProbA": 0.509,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Wojciech Gluszek (51%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1476 (n=30) vs 1469 (n=18)"
    },
    {
      "id": "rec-cz-8lk2xsdz0lyizq3",
      "date": "2026-07-10",
      "startTime": 1783726200,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "8lk2xsdz0lyizq3",
      "playerA": "Petr Sebera",
      "playerB": "Marek Chlebecek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 46 and 6 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1443 (n=46) vs 1564 (n=6)"
    },
    {
      "id": "rec-cz-9gkl1sjxl2ysmqx",
      "date": "2026-07-10",
      "startTime": 1783726200,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "9gkl1sjxl2ysmqx",
      "playerA": "Levicky, Matej",
      "playerB": "Jaroslav Strnad",
      "myProbA": 0.579,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Levicky, Matej (58%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1532 (n=13) vs 1476 (n=19)"
    },
    {
      "id": "rec-cz-l6keds429olfv75",
      "date": "2026-07-10",
      "startTime": 1783726200,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "l6keds429olfv75",
      "playerA": "Darin Kyryl",
      "playerB": "Ondrej Kucirek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 22 and 6 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1578 (n=22) vs 1497 (n=6)"
    },
    {
      "id": "rec-pl-527rxsrde3jh47e",
      "date": "2026-07-10",
      "startTime": 1783726200,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "527rxsrde3jh47e",
      "playerA": "Damian Fira",
      "playerB": "Orszulik, Jan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 25 and 9 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1461 (n=25) vs 1482 (n=9)"
    },
    {
      "id": "rec-pl-o07d1s4rdn5fm7n",
      "date": "2026-07-10",
      "startTime": 1783726500,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "o07d1s4rdn5fm7n",
      "playerA": "Jakub Witkowski",
      "playerB": "Patryk Jendrzejewski",
      "myProbA": 0.315,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Patryk Jendrzejewski (69%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1425 (n=18) vs 1561 (n=28)"
    },
    {
      "id": "rec-pl-o17p1slw080ty7j",
      "date": "2026-07-10",
      "startTime": 1783726500,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "o17p1slw080ty7j",
      "playerA": "Lukasz Pyda",
      "playerB": "Dawid Pyrek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 7 and 28 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1426 (n=7) vs 1524 (n=28)"
    },
    {
      "id": "rec-pl-vmqyosx1jxeagk9",
      "date": "2026-07-10",
      "startTime": 1783727100,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "vmqyosx1jxeagk9",
      "playerA": "Sebastian Baran",
      "playerB": "Mikolaj Lukaszewski",
      "myProbA": 0.671,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Sebastian Baran (67%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1579 (n=19) vs 1456 (n=45)"
    },
    {
      "id": "rec-pl-o17p1slw0l0uy7j",
      "date": "2026-07-10",
      "startTime": 1783727100,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "o17p1slw0l0uy7j",
      "playerA": "Schaniel Krzysztof",
      "playerB": "Sokolowski, Oskar",
      "myProbA": 0.554,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Schaniel Krzysztof (55%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1533 (n=46) vs 1495 (n=36)"
    },
    {
      "id": "rec-pl-wv78lsy4p1ntokr",
      "date": "2026-07-10",
      "startTime": 1783727700,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "wv78lsy4p1ntokr",
      "playerA": "Nowak Jakub",
      "playerB": "Jakub Michalski",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 35 and 4 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1456 (n=35) vs 1433 (n=4)"
    },
    {
      "id": "rec-pl-jr7o1sog6olbgk0",
      "date": "2026-07-10",
      "startTime": 1783727700,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "jr7o1sog6olbgk0",
      "playerA": "Jakub Zochniak",
      "playerB": "Marcin Marchlewski",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 18 and 6 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1485 (n=18) vs 1474 (n=6)"
    },
    {
      "id": "rec-cz-jr7o1sogxg6bgk0",
      "date": "2026-07-11",
      "startTime": 1783728000,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "jr7o1sogxg6bgk0",
      "playerA": "Vladimir Cermak",
      "playerB": "Trefny Jan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 9 and 5 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1491 (n=9) vs 1462 (n=5)"
    },
    {
      "id": "rec-cz-xvkjds1wr6rf8k9",
      "date": "2026-07-11",
      "startTime": 1783728000,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "xvkjds1wr6rf8k9",
      "playerA": "David Horak",
      "playerB": "Adam Svoboda",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 13 and 1 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1514 (n=13) vs 1517 (n=1)"
    },
    {
      "id": "rec-pl-jr7o1sog6wlhgk0",
      "date": "2026-07-11",
      "startTime": 1783728000,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "jr7o1sog6wlhgk0",
      "playerA": "Michal Natkaniec",
      "playerB": "Wozniczka, Marcin",
      "myProbA": 0.493,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Wozniczka, Marcin (51%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1446 (n=17) vs 1450 (n=16)"
    },
    {
      "id": "rec-cz-34kges4lpv2ceqo",
      "date": "2026-07-11",
      "startTime": 1783728000,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "34kges4lpv2ceqo",
      "playerA": "Lubor Sulava",
      "playerB": "Josef Pelikan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 24 and 5 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1569 (n=24) vs 1452 (n=5)"
    },
    {
      "id": "rec-pl-jek35sp46mvi97o",
      "date": "2026-07-11",
      "startTime": 1783728600,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "jek35sp46mvi97o",
      "playerA": "Wojciech Gluszek",
      "playerB": "Mikolaj Lukaszewski",
      "myProbA": 0.529,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Wojciech Gluszek (53%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1476 (n=30) vs 1456 (n=45)"
    },
    {
      "id": "rec-pl-vrqwys2do00b4kn",
      "date": "2026-07-11",
      "startTime": 1783728600,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "vrqwys2do00b4kn",
      "playerA": "Pawel Adamus",
      "playerB": "Mateusz Sikon",
      "myProbA": 0.609,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Pawel Adamus (61%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1465 (n=32) vs 1388 (n=36)"
    },
    {
      "id": "rec-pl-9gkl1sjx0j3smqx",
      "date": "2026-07-11",
      "startTime": 1783729200,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "9gkl1sjx0j3smqx",
      "playerA": "Jakub Witkowski",
      "playerB": "Marcin Marchlewski",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 18 and 6 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1425 (n=18) vs 1474 (n=6)"
    },
    {
      "id": "rec-pl-9gkl1sjx0w3bmqx",
      "date": "2026-07-11",
      "startTime": 1783729200,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "9gkl1sjx0w3bmqx",
      "playerA": " Adam Ruszkiewicz",
      "playerB": "Roman Wiza",
      "myProbA": 0.558,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK:  Adam Ruszkiewicz (56%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1508 (n=30) vs 1468 (n=24)"
    },
    {
      "id": "rec-pl-ndkzlsdpzvoixq3",
      "date": "2026-07-11",
      "startTime": 1783729500,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "ndkzlsdpzvoixq3",
      "playerA": "Jacek Oracz",
      "playerB": "Krzysztof Malcher",
      "myProbA": 0.739,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Jacek Oracz (74%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1675 (n=37) vs 1494 (n=11)"
    },
    {
      "id": "rec-cz-6975ysxpw46fgq2",
      "date": "2026-07-11",
      "startTime": 1783729800,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "6975ysxpw46fgq2",
      "playerA": "Patrik Pycha ",
      "playerB": "Marek Chlebecek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 11 and 6 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1539 (n=11) vs 1564 (n=6)"
    },
    {
      "id": "rec-cz-vmqyosx1e32ugk9",
      "date": "2026-07-11",
      "startTime": 1783729800,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "vmqyosx1e32ugk9",
      "playerA": "Pavel Kulhanek",
      "playerB": "Jaroslav Strnad",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 9 and 19 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1594 (n=9) vs 1476 (n=19)"
    },
    {
      "id": "rec-cz-ndqm1sye4l6arqv",
      "date": "2026-07-11",
      "startTime": 1783729800,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ndqm1sye4l6arqv",
      "playerA": "Radek Bartunek",
      "playerB": "Ondrej Kucirek",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 17 and 6 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1388 (n=17) vs 1497 (n=6)"
    },
    {
      "id": "rec-pl-edq08swrm28aekx",
      "date": "2026-07-11",
      "startTime": 1783730100,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "edq08swrm28aekx",
      "playerA": "Piotr Staniszewski",
      "playerB": "Sebastian Baran",
      "myProbA": 0.347,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Sebastian Baran (65%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1469 (n=18) vs 1579 (n=19)"
    },
    {
      "id": "rec-pl-6975ysxp3r0igq2",
      "date": "2026-07-11",
      "startTime": 1783730100,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "6975ysxp3r0igq2",
      "playerA": "Mariusz Baron",
      "playerB": "Sokolowski, Oskar",
      "myProbA": 0.461,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Sokolowski, Oskar (54%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1468 (n=57) vs 1495 (n=36)"
    },
    {
      "id": "rec-pl-8lk2xsdzg34fzq3",
      "date": "2026-07-11",
      "startTime": 1783730700,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "8lk2xsdzg34fzq3",
      "playerA": "Damian Fira",
      "playerB": "Nowak Jakub",
      "myProbA": 0.507,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Damian Fira (51%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1461 (n=25) vs 1456 (n=35)"
    },
    {
      "id": "rec-pl-63kv1s5pm5osxke",
      "date": "2026-07-11",
      "startTime": 1783730700,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "63kv1s5pm5osxke",
      "playerA": "Lukasz Pyda",
      "playerB": "Wozniczka, Marcin",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 7 and 16 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1426 (n=7) vs 1450 (n=16)"
    },
    {
      "id": "rec-pl-wv78lsy4pgnaokr",
      "date": "2026-07-11",
      "startTime": 1783730700,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "wv78lsy4pgnaokr",
      "playerA": "Patryk Jendrzejewski",
      "playerB": "Jakub Zochniak",
      "myProbA": 0.607,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Patryk Jendrzejewski (61%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1561 (n=28) vs 1485 (n=18)"
    },
    {
      "id": "rec-cz-ndkzlsdpmy9axq3",
      "date": "2026-07-11",
      "startTime": 1783731600,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "ndkzlsdpmy9axq3",
      "playerA": "Josef Pelikan",
      "playerB": "Levicky, Matej",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 5 and 13 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1452 (n=5) vs 1532 (n=13)"
    },
    {
      "id": "rec-cz-6975ysxpwe6agq2",
      "date": "2026-07-11",
      "startTime": 1783731600,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "6975ysxpwe6agq2",
      "playerA": "Trefny Jan",
      "playerB": "Petr Sebera",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 5 and 46 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1462 (n=5) vs 1443 (n=46)"
    },
    {
      "id": "rec-cz-j3742s6g82gfgko",
      "date": "2026-07-11",
      "startTime": 1783731600,
      "event": "Czech Liga Pro",
      "circuit": "czech",
      "matchId": "j3742s6g82gfgko",
      "playerA": "Adam Svoboda",
      "playerB": "Darin Kyryl",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 1 and 22 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1517 (n=1) vs 1578 (n=22)"
    },
    {
      "id": "rec-pl-63kv1s5pm6ohxke",
      "date": "2026-07-11",
      "startTime": 1783731600,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "63kv1s5pm6ohxke",
      "playerA": "Wojciech Gluszek",
      "playerB": "Sebastian Baran",
      "myProbA": 0.355,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Sebastian Baran (64%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1476 (n=30) vs 1579 (n=19)"
    },
    {
      "id": "rec-pl-jek35sp46pvs97o",
      "date": "2026-07-11",
      "startTime": 1783731600,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "jek35sp46pvs97o",
      "playerA": "Schaniel Krzysztof",
      "playerB": "Pawel Adamus",
      "myProbA": 0.596,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Schaniel Krzysztof (60%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1533 (n=46) vs 1465 (n=32)"
    },
    {
      "id": "rec-pl-j3742s6g14rbgko",
      "date": "2026-07-11",
      "startTime": 1783732200,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "j3742s6g14rbgko",
      "playerA": "Michal Natkaniec",
      "playerB": "Jacek Oracz",
      "myProbA": 0.211,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "MODEL PICK: Jacek Oracz (79%) — odds not found; enter odds in app",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1446 (n=17) vs 1675 (n=37)"
    },
    {
      "id": "rec-pl-o07d1s4rd45sm7n",
      "date": "2026-07-11",
      "startTime": 1783732200,
      "event": "TT Elite Series",
      "circuit": "polish",
      "matchId": "o07d1s4rd45sm7n",
      "playerA": "Roman Wiza",
      "playerB": "Orszulik, Jan",
      "myProbA": null,
      "marketProbA": null,
      "bestOdds": null,
      "edge": null,
      "rec": "NO BET (Elo data too thin: 24 and 9 rated matches, need 10)",
      "units": 0,
      "pickName": null,
      "grade": "C",
      "reasoning": "Elo 1468 (n=24) vs 1482 (n=9)"
    }
  ],
  "bets": [
    {
      "id": "bet-rec-cz-ndkzlsdpmp9axq3",
      "recId": "rec-cz-ndkzlsdpmp9axq3",
      "date": "2026-07-10",
      "event": "Czech Liga Pro",
      "playerA": "Vaclav Nohejl",
      "playerB": "Urbaniec Radim",
      "pick": "Vaclav Nohejl",
      "odds": 1.83,
      "units": 1.0,
      "grade": "C",
      "status": "loss",
      "circuit": "czech",
      "notes": "auto-logged by engine [rec:rec-cz-ndkzlsdpmp9axq3] | Urbaniec Radim won 1-3 (auto-settled)",
      "matchId": "ndkzlsdpmp9axq3"
    },
    {
      "id": "bet-rec-cz-l6keds42e6otv75",
      "recId": "rec-cz-l6keds42e6otv75",
      "date": "2026-07-10",
      "event": "TT Cup",
      "playerA": "Tomas Rein",
      "playerB": "Jean-Baptiste Cousin",
      "pick": "Tomas Rein",
      "odds": 3.4,
      "units": 1.0,
      "grade": "C",
      "status": "loss",
      "circuit": "czech",
      "notes": "auto-logged by engine [rec:rec-cz-l6keds42e6otv75] | Jean-Baptiste Cousin won 1-3 (auto-settled)",
      "matchId": "l6keds42e6otv75"
    },
    {
      "id": "bet-rec-20260710-fumiya-igarashi-leo-de-nodrest",
      "recId": "rec-20260710-fumiya-igarashi-leo-de-nodrest",
      "date": "2026-07-10",
      "startTime": 1783718100,
      "event": "WTT Feeder Asuncion, MS",
      "playerA": "Leo de Nodrest",
      "playerB": "Fumiya Igarashi",
      "pick": "Leo de Nodrest",
      "odds": 1.28,
      "units": 1.0,
      "grade": "C",
      "status": "win",
      "circuit": "wtt",
      "notes": "auto-logged by engine [rec:rec-20260710-fumiya-igarashi-leo-de-nodrest] | Leo de Nodrest won 3-0 (auto-settled)",
      "matchId": "jr7o1soglxrigk0"
    }
  ]
};
